#!/bin/bash

echo "=== Applying ingress configuration ==="
echo ""
echo "This script will help update the ingress to route learnbytesting.ai to webapp-ssr"
echo ""

echo "Steps to apply the ingress:"
echo ""
echo "1. First, get your kubeconfig:"
echo "   doctl kubernetes cluster kubeconfig save --expiry-seconds 600 3b23a2dd-3391-4d1a-a478-e2a5564de99c"
echo ""
echo "2. Apply the ingress configuration:"
echo "   kubectl apply -f /mnt/c/Users/Renato/repos/lbt/webapp/lbt_ingress.yaml"
echo ""
echo "3. Check the ingress status:"
echo "   kubectl get ingress learnbytest-ingress"
echo ""
echo "4. Verify the webapp-ssr service exists:"
echo "   kubectl get svc webapp-ssr"
echo ""
echo "Expected output for service:"
echo "NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE"
echo "webapp-ssr   ClusterIP   10.x.x.x        <none>        4000/TCP   XXm"
echo ""
echo "5. Check if pods are running:"
echo "   kubectl get pods -l app.kubernetes.io/name=webapp-ssr"
echo ""
echo "6. If pods are running but site still shows WordPress, check pod logs:"
echo "   kubectl logs -l app.kubernetes.io/name=webapp-ssr --tail=50"
echo ""
echo "7. Force a refresh (DNS cache might be an issue):"
echo "   - Try in incognito/private browsing mode"
echo "   - Or wait a few minutes for DNS propagation"
echo ""
echo "Note: The ingress yaml already has webapp-ssr configured for learnbytesting.ai"